In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import RegexpTokenizer
import re
import string
import random
from PIL import Image
import requests
from io import BytesIO
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
%matplotlib inline

In [2]:
df = pd.read_csv('symptoms.csv')
df.head()

disease                                           symptoms  \
0           flu  fever,cough,sore throat,runny or stuffy nose,m...   
1    bronchitis  cough,mucus production,shortness of breath,che...   
2     pneumonia  fever,cough,shortness of breath,chest pain,fat...   
3  heart attack  chest pain,shortness of breath,nausea,vomiting...   
4        stroke  sudden weakness,numbness on one side of the bo...   

                                               cures  \
0           over-the-counter medications,rest,fluids   
1  antibiotics,over-the-counter medications,rest,...   
2  antibiotics,over-the-counter medications,rest,...   
3                         emergency medical services   
4                         emergency medical services   

                        doctor     risk level  
0    family doctor,urgent care      low (0.1%  
1  family doctor,pulmonologist      low (0.5%  
2  family doctor,pulmonologist  moderate (1%)  
3                 cardiologist     high (20%)  
4                 neurologist      high (15%)

In [3]:
# df_dr=pd.read_csv('doctor.csv')
# df

In [4]:
li={'Tag':['sudden numbness or weakness in the face,confusion and memory loss,pink eye,difficulty speaking,pain in body, fever, cough,headache,cant walk,vomiting']}
df1=pd.DataFrame(li)
df1

Tag
0  sudden numbness or weakness in the face,confus...

In [5]:
# df1=pd.read_csv('Stroke_Test.csv')
# df1.head()

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.feature_extraction.text import TfidfVectorizer
# vec=TfidfVectorizer(max_features=200)
vec=CountVectorizer(max_features=200)
vecs1=vec.fit_transform(df["symptoms"]).toarray()
vecs2=vec.transform(df1["Tag"]).toarray()
print(vecs1.shape)
print(vecs2.shape)
print(vecs1)
print(vecs2)

(98, 200)
(1, 200)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0
  0 0 0 1 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
  0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]]


In [7]:
from sklearn.metrics.pairwise import cosine_similarity
new_vec1=vecs1[:20]
new_vec2=vecs2[:20]
sim=cosine_similarity(vecs1,vecs2)

In [8]:
sim

array([[0.25197632],
       [0.15430335],
       [0.23145502],
       [0.14547859],
       [0.6172134 ],
       [0.25031309],
       [0.05455447],
       [0.48304589],
       [0.32991444],
       [0.26726124],
       [0.10910895],
       [0.05832118],
       [0.        ],
       [0.48304589],
       [0.        ],
       [0.        ],
       [0.43643578],
       [0.32991444],
       [0.09759001],
       [0.        ],
       [0.21821789],
       [0.        ],
       [0.29160592],
       [0.3003757 ],
       [0.15430335],
       [0.19738551],
       [0.25031309],
       [0.06299408],
       [0.17817416],
       [0.        ],
       [0.24743583],
       [0.08908708],
       [0.        ],
       [0.34503278],
       [0.05455447],
       [0.        ],
       [0.16495722],
       [0.        ],
       [0.15430335],
       [0.09759001],
       [0.43643578],
       [0.27914526],
       [0.08247861],
       [0.10910895],
       [0.17496355],
       [0.25197632],
       [0.09759001],
       [0.476

In [9]:
sim.shape

(98, 1)

In [10]:
# sim[0:97,0:1]

In [11]:
# lop=0
# predli=[]
# while lop!=40:
#   ppp=lop+1
#   li1=sorted(list(enumerate(sim[0:97,lop:ppp])), reverse = True, key = lambda x : x[1])[0:6]
#   lit=li1[0]
#   ll=list(df['disease'].iloc[lit[0]:(lit[0]+1)])
#   predli.append(ll[0])
#   print(ll)
#   lop=lop+1

In [12]:
# predli

In [13]:
# y=df1.Disease
# y

In [14]:
# report = classification_report(y,predli)
# print(report)

In [15]:
li1=sorted(list(enumerate(sim[:])), reverse = True, key = lambda x : x[1])[0:6]
li1

[(4, array([0.6172134])),
 (83, array([0.50709255])),
 (81, array([0.49487166])),
 (7, array([0.48304589])),
 (13, array([0.48304589])),
 (65, array([0.48304589]))]

In [16]:
lit=li1[0]
lit[0]

4

In [17]:
ll=list(df['disease'].iloc[lit[0]:(lit[0]+1)])
ll

['stroke']